% Script validation_bandwidth_dependence
%
% Verification of Tonality_Aures1985 against the dependence of tonality on the
% bandwidth of the tonal component. The reference is the subjective data of
% Hastings [1], Table B.52 of the thesis, third tone test, 17 subjects, direct
% scaling from 0 to 10. That table carries its own anchors, a pure tone at 8.0
% and broadband noise at 2.0, and Hastings scales them to 1 and 0 (thesis
% p. 69), so the reference used here is (score - 2)/6.
%
% Test signals: trapezoidal bandpass noise centred at 700 Hz with a roll-off of
% 100 dB per octave and a peak bandwidth from 1 to 200 per cent of the critical
% bandwidth, equalised to 16 sone as in the experiment. Signals are generated by
% the script and no dataset is needed.
%
% What the model says: the tonality of a narrow band of noise falls as the band
% widens, Aures [2] eq. (7) and Fig. 6, through the weighting w1(dz).
%
% References
%   [1] Hastings, A. L. (2004). Sound quality of diesel engines. PhD thesis,
%       Purdue University, ProQuest 3154642. See also Hastings, A., Lee, K. H.,
%       Davies, P., & Surprenant, A. M. (2003). Measurement of the attributes of
%       complex tonal components commonly found in product sound. Noise Control
%       Engineering Journal, 51(4), 195-209.
%   [2] Aures, W. (1985). Berechnungsverfahren fuer den sensorischen Wohlklang
%       beliebiger Schallsignale. Acta Acustica united with Acustica, 59(2),
%       130-141.
%
% Author: Sergio Aguirre, September 2026
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear all; close all; clc; %#ok<CLALL>

fs  = 48000;
N   = fs;                 % one second per signal
fc  = 700;                % centre frequency of the third tone test
roll = 100;               % roll-off of the trapezoidal filter, dB per octave
N_target = 16;            % loudness of the test signals, sone
CBW = 25 + 75*(1 + 1.4*(fc/1000)^2)^0.69;   % critical bandwidth, Zwicker

pct   = [1 5 10 15 25 50 75 100 150 200];   % peak bandwidth, per cent of CBW
score = [5.5 5.3 5.5 5.9 5.4 5.2 5.0 4.5 4.6 4.3];  % Table B.52, 700 Hz column
ref   = (score - 2)/6;    % scaled to the anchors of the table

rng(42);                  % the spectra are random, so the run is repeatable
f  = (0:N-1).'*fs/N; f(f > fs/2) = f(f > fs/2) - fs;
fa = abs(f);

%% pure tone at the same loudness, the upper anchor of the scale
t = (0:N-1).'/fs;
x = sin(2*pi*fc*t);
K_tone = il_tonality_at_loudness(x, fs, N_target);

%% the bandwidth series
K = zeros(size(pct));
for i = 1:numel(pct)
    bw  = CBW*pct(i)/100;
    mag = zeros(N,1);
    inband = fa >= fc-bw/2 & fa <= fc+bw/2;
    mag(inband) = 1;
    skirt = ~inband & fa > 0;
    oct = abs(log2(max(fa(skirt),1)/fc)) - log2((fc+bw/2)/fc);
    oct(oct < 0) = 0;
    mag(skirt) = 10.^(-roll*oct/20);
    ph = exp(1j*2*pi*rand(N,1)); ph(1) = 1;
    X  = mag.*ph; X(N/2+2:end) = conj(flipud(X(2:N/2)));
    K(i) = il_tonality_at_loudness(real(ifft(X)), fs, N_target);
end

rel = K/K_tone;           % tonality relative to the pure tone of the same loudness

%% report
fprintf('Trapezoidal noise at %d Hz, roll-off %d dB per octave, %d sone\n', fc, roll, N_target);
fprintf('critical bandwidth %.1f Hz, pure tone gives %.4f t.u.\n\n', CBW, K_tone);
fprintf('%8s %10s %12s %12s %10s\n', '% CBW', 'BW (Hz)', 'K (t.u.)', 'K/K tone', 'reference');
for i = 1:numel(pct)
    fprintf('%8d %10.1f %12.4f %12.3f %10.3f\n', pct(i), CBW*pct(i)/100, K(i), rel(i), ref(i));
end

%% verdict
tol_mono = 0.02;          % allowance on the monotonic decrease, relative units
if all(diff(rel) <= tol_mono)
    fprintf('\nCHECK 1 PASSED: the tonality does not rise as the band widens\n');
else
    fprintf('\nCHECK 1 FAILED: the tonality rises as the band widens, %s\n', mat2str(round(rel,3)));
end
gap = mean(ref) - mean(rel);
fprintf('CHECK 2 REPORT: mean of the reference %.3f, mean of the model %.3f, gap %.3f\n', ...
        mean(ref), mean(rel), gap);
fprintf('                span of the reference %.3f, span of the model %.3f\n', ...
        max(ref)-min(ref), max(rel)-min(rel));

%% plot
figure('color','w');
plot(pct, ref, 'k*-', 'MarkerSize', 8); hold on;
plot(pct, rel, 'ko:', 'MarkerSize', 8);
set(gca,'XScale','log'); xlim([1 200]); ylim([0 1.1]); grid off;
xlabel('Peak bandwidth (per cent of the critical bandwidth)','Interpreter','Latex');
ylabel('Tonality relative to the pure tone','Interpreter','Latex');
legend({'Reference, Hastings Table B.52','SQAT'},'Location','SouthWest','Interpreter','Latex');
legend boxoff;

%% local function
function K = il_tonality_at_loudness(x, fs, N_target)
% brings x to the target loudness by bisection on the gain, then returns the
% time averaged tonality
x  = x/rms(x);
lo = 20e-6*10^(30/20); hi = 20e-6*10^(110/20);
for it = 1:14
    g = sqrt(lo*hi);
    if Loudness_ISO532_1(x*g, fs, 0, 1, 0, 0).Loudness < N_target, lo = g; else, hi = g; end
end
K = Tonality_Aures1985(x*sqrt(lo*hi), fs, 0, 0, false).Kmean;
end
