% Script validation_internal_consistency
%
% Verification of Tonality_Aures1985 against properties that follow from the
% definition of the model, in the spirit of validation_Do_SLM_time_weighting.m
% of the sound level meter: the reference is derived here and not tabulated
% anywhere, so the outcome is a statement of internal consistency. Every signal
% is generated by the script and no dataset is needed.
%
%   1. Definitional anchor. A 1 kHz pure tone at 60 dB SPL has a tonality of
%      1 t.u. by definition, Aures [1], section 2.3.
%   2. Non-tonal reference. Broadband noise carries no tonal component.
%   3. Determinism. The metric is a function of its input, so two calls on the
%      same signal return the same value.
%   4. Number of components. W_T sums over the tonal components, Aures [1]
%      eq. (11), so adding tones in separate critical bands cannot lower it.
%   5. Frequency grid. The analysis grid is an artefact of the implementation,
%      so the tonality of a pure tone cannot depend on where its frequency
%      falls between two bins of the FFT.
%
% Reference
%   [1] Aures, W. (1985). Berechnungsverfahren fuer den sensorischen Wohlklang
%       beliebiger Schallsignale. Acta Acustica united with Acustica, 59(2),
%       130-141.
%
% Author: Sergio Aguirre, September 2026
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear all; close all; clc; %#ok<CLALL>

fs = 48000;
T  = 1;
t  = (0:1/fs:T-1/fs).';
il_tone = @(f,spl) sqrt(2)*20e-6*10^(spl/20)*sin(2*pi*f*t);

tol_jnd    = 0.10;   % t.u., tonality JND used as the anchor tolerance
tol_noise  = 0.05;   % t.u., ceiling for broadband noise
tol_grid   = 0.10;   % t.u., tonality JND, the budget for the spread across one bin
nfail = 0;

%% Check 1: definitional anchor, 1 kHz at 60 dB SPL gives 1 t.u.
K = Tonality_Aures1985(il_tone(1000,60), fs, 0, 0, false).Kmean;
if abs(K-1) <= tol_jnd
    fprintf('CHECK 1 PASSED: anchor K = %.4f t.u., within %.2f of 1 t.u.\n', K, tol_jnd);
else
    fprintf('CHECK 1 FAILED: anchor K = %.4f t.u., expected 1 t.u. within %.2f\n', K, tol_jnd);
    nfail = nfail + 1;
end

%% Check 2: broadband noise is not tonal
rng(0);
wn = randn(numel(t),1); wn = wn/rms(wn)*20e-6*10^(70/20);
K = Tonality_Aures1985(wn, fs, 0, 0, false).Kmean;
if K <= tol_noise
    fprintf('CHECK 2 PASSED: white noise at 70 dB SPL gives K = %.4f t.u.\n', K);
else
    fprintf('CHECK 2 FAILED: white noise gives K = %.4f t.u., expected at most %.2f\n', K, tol_noise);
    nfail = nfail + 1;
end

%% Check 3: the same input returns the same output
insig = il_tone(1000,85) + 0.03*randn(numel(t),1)*20e-6*10^(85/20);
A = Tonality_Aures1985(insig, fs, 0, 0, false);
B = Tonality_Aures1985(insig, fs, 0, 0, false);
if isequal(A.InstantaneousTonality, B.InstantaneousTonality)
    fprintf('CHECK 3 PASSED: two calls on the same input agree bit for bit\n');
else
    d = max(abs(A.InstantaneousTonality-B.InstantaneousTonality));
    fprintf('CHECK 3 FAILED: two calls differ by up to %.2e t.u. on the same input\n', d);
    nfail = nfail + 1;
end

%% Check 4: adding tones cannot lower the tonal weighting
f_sets = {1000, [1000 2000], [1000 2000 3000], [500 1000 1500 2000 2500]};
WT = zeros(1,numel(f_sets));
for i = 1:numel(f_sets)
    x = zeros(numel(t),1);
    for f = f_sets{i}, x = x + il_tone(f,60); end
    WT(i) = mean(Tonality_Aures1985(x, fs, 0, 0, false).TonalWeighting);
end
if all(diff(WT) >= -1e-6)
    fprintf('CHECK 4 PASSED: W_T does not fall with the number of tones, %s\n', mat2str(round(WT,4)));
else
    fprintf('CHECK 4 FAILED: W_T falls as tones are added, %s for 1, 2, 3 and 5 tones\n', mat2str(round(WT,4)));
    nfail = nfail + 1;
end

%% Check 5: the tonality of a tone does not depend on the FFT bin position
f_grid = [1000 1001.6 1003.125 1004.5 1006.25];
Kg = zeros(1,numel(f_grid));
for i = 1:numel(f_grid)
    Kg(i) = Tonality_Aures1985(il_tone(f_grid(i),60), fs, 0, 0, false).Kmean;
end
spread = max(Kg) - min(Kg);
if spread <= tol_grid
    fprintf('CHECK 5 PASSED: K spreads %.4f t.u. across one FFT bin, within the %.2f JND\n', spread, tol_grid);
else
    fprintf('CHECK 5 FAILED: K spreads %.4f t.u. across one FFT bin, %s\n', spread, mat2str(round(Kg,4)));
    nfail = nfail + 1;
end
fprintf('         achieved spread %.4f t.u. (0.5049 before the tones were removed\n', spread);
fprintf('         from the windowed spectrum; a spread of zero needs the tone to be\n');
fprintf('         subtracted in the time domain, which is not done here)\n');

%% Summary
fprintf('\n%d of 5 checks failed\n', nfail);
