% Script validation_signal_to_noise_ratio
%
% - This routine verifies the tonality model of Aures against Fig. 1(a) of
%   Hastings et al. (2003): a pure tone of 85 dB SPL at 1 kHz in broadband
%   noise, as a function of the signal to noise ratio in the critical band
%   centered about the tone. The test signals are generated by this script,
%   so no external dataset is needed: the noise is white and its level is
%   set so that the power it carries inside the critical band gives the
%   wanted ratio.
%   
% - The reference data is taken from:
%   Aaron Hastings, Kyoung Hoon Lee, Patricia Davies, and Aimée M. Surprenant
%   "Measurement of the attributes of complex tonal components commonly 
%   found in product sound" Noise Control Eng. J. 51, 2003.
%
% - Tonality computed using 
%   OUT = Tonality_Aures1985(insig,fs,LoudnessField,time_skip,show)
%   type <help Tonality_Aures1985> for more info
%
% Author: Gil Felix Greco, Braunschweig, 22.03.2023
% Modified: Sergio Aguirre, September 2026 - the test signals are generated
%   here, with the level of the noise referred to the critical band as in [1]
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear all; close all; clc;

%% save settings

save_figs = 0;

%% define input/output paths

dir_out = [fileparts(mfilename('fullpath')) filesep];

%% reference data 
% Source: Hastings et al. (2003), fig. 1

ref=[
0  0.015823397764229252
10  0.07533719859035015
20  0.20912727004956122
30  0.40794580496985177
40  0.5923422380983235
50  0.7627954783966964
60  0.8820348816074157
70  0.9558121564573688
80  0.9825276908062728
     ];

%% generate the test signals
% A pure tone of Ltone dB SPL at fc, plus white noise whose level inside the
% critical band centered at fc sits SNR dB below the tone. White noise spreads
% its power evenly over frequency, so the total level of the noise is the level
% wanted inside the band plus 10*log10((fs/2)/CB), with CB the critical
% bandwidth after Zwicker.

fs    = 44100;   % sampling frequency (Hz)
L     = 5;       % signal length (s)
fc    = 1000;    % frequency of the tone (Hz)
Ltone = 85;      % level of the tone (dB SPL), the series of Fig. 1(a) of [1]
p0    = 2e-5;    % reference pressure (Pa)
rng(1);          % the noise is random, so that the run is repeatable

CB   = 25 + 75*(1 + 1.4*(fc/1000)^2)^0.69;   % critical bandwidth at fc (Hz)
t    = (0:1/fs:L-1/fs).';
tone = sqrt(2)*p0*10^(Ltone/20)*sin(2*pi*fc*t);
wn   = randn(numel(t),1); wn = wn/rms(wn);   % white noise of unit rms

SNR       = ref(:,1).';          % dB, inside the critical band, as in [1]
N_signals = numel(SNR);
insigs    = zeros(numel(t),N_signals);

for i = 1:N_signals
    L_band      = Ltone - SNR(i);                  % noise level inside the band
    L_total     = L_band + 10*log10((fs/2)/CB);    % level of the white noise
    insigs(:,i) = tone + wn*p0*10^(L_total/20);
end

%% compute tonality
for i=1:N_signals
    
    bPlot_figure = 0; % set to 1 to plot the raw outputs
    T{i} = Tonality_Aures1985(insigs(:,i),fs,0,0,bPlot_figure);
    results(i)= [T{i}.Kmean]; % create vector with time-averaged tonality values
    
end

%% plot

h  =figure;
set(h,'Units','Inches');
pos = get(h,'Position');
set(h,'PaperPositionMode','Auto','PaperUnits','Inches','PaperSize',[pos(3), pos(4)])
 
yyaxis left

% reference results
a=plot( ref(:,1),ref(:,2),'k*-','MarkerSize',8);hold on;

% SQAT
b=plot(0:10:80,results,'ko:','MarkerSize',8);

% dummy plot to make x-axis larger
plot(1,0.1);hold on;
plot(5,0.1);hold on;

ylim([0 1.1]);
xlim([0 80]);

ylabel('Time-averaged tonality, $K_{\mathrm{mean}}$ (t.u.)','Interpreter','Latex');
xlabel(sprintf('Signal-to-noise ratio in the critical band\n centered about the tone (dB)'),'Interpreter','Latex'); 
grid off

legend([a,b],{ 'Literature',...
        'SQAT'},...
        'Location','SE','Interpreter','Latex');

legend boxoff

yyaxis right

plot(0:10:80,results'-ref(:,2),'o-','MarkerSize',4,'MarkerFaceColor',[0.85,0.33,0.10],'HandleVisibility','off');hold on;

ylim([-0.2 0.2]);

ylabel('SQAT minus Reference (t.u.)','Interpreter','Latex');

ax = gca;
ax.XAxis.MinorTick = 'on';
ax.XAxis.MinorTickValues =  0:10:80;

set(ax,'XTick',[0 20 40 60 80]);     
set(ax,'YTick',[0 .2 .4 .6 .8 1]);

yticks([-0.2 -0.1 0 0.1 0.2])

ax.YAxis(1).Color = 'k';

set(gcf,'color','w');

%%

if save_figs==1
    if ~exist(dir_out,'dir')
        mkdir(dir_out);
    end
    figures_dir = [dir_out 'figs' filesep];
    if ~exist(figures_dir,'dir')
        mkdir(figures_dir);
    end
    
    figname_short = 'tonality_validation_SNR_tone_85dBSPL_1khz';
    figname_out = [figures_dir figname_short];
    
%     saveas(gcf, figname_out, 'fig');
%     saveas(gcf, figname_out, 'pdf');
    saveas(gcf, figname_out, 'png');
    
    fprintf('%s.m: figure %s was saved on disk\n\t(full name: %s)\n',mfilename,figname_short,figname_out);
end
